stages:
  - build
  - test
  - deploy
  - dast

dast:
  stage: dast
  variables:
    GIT_STRATEGY: none
  allow_failure: true
  script:
    - export WEBSITE=${WEBSITE:-$(cat environment_url.txt)}
    - echo $WEBSITE
    - rm script || true
    - wget https://raw.githubusercontent.com/asafbenhaim/sokoban/master/script
    - chmod +x script
    - ./script
    - echo wtc
  artifacts:
    reports:
      dast: gl-dast-report.json
