stages:
  - build
  - test
  - deploy
  - dast

dast:
  stage: dast
  variables:
    GIT_STRATEGY: none
  allow_failure: true
  script:
    - export DAST_WEBSITE=${DAST_WEBSITE:-$(cat environment_url.txt)}
    - echo $DAST_WEBSITE
    - curl -I $DAST_WEBSITE | grep "200 ok"
    - curl -I $DAST_WEBSITE | grep -q "200 ok"
  artifacts:
    reports:
      dast: gl-dast-report.json
