stages:
  - build
  - test
  - deploy
  - dast

dast:
  stage: dast
  variables:
    GIT_STRATEGY: none
  allow_failure: true
  script:
    - export DAST_WEBSITE=${DAST_WEBSITE:-$(cat environment_url.txt)}
    - echo $DAST_WEBSITE
    - echo 123123123 > gl-dast-report.json
  artifacts:
    reports:
      dast: gl-dast-report.json
